/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package srf.transpiler.fortxtrans.fortXTrans;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Init</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.ArrayInit#getLeft <em>Left</em>}</li>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.ArrayInit#getType <em>Type</em>}</li>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.ArrayInit#getSizes <em>Sizes</em>}</li>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.ArrayInit#getFiller <em>Filler</em>}</li>
 * </ul>
 *
 * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getArrayInit()
 * @model
 * @generated
 */
public interface ArrayInit extends Expr
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Expr)
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getArrayInit_Left()
   * @model containment="true"
   * @generated
   */
  Expr getLeft();

  /**
   * Sets the value of the '{@link srf.transpiler.fortxtrans.fortXTrans.ArrayInit#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Expr value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(SimpleName)
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getArrayInit_Type()
   * @model containment="true"
   * @generated
   */
  SimpleName getType();

  /**
   * Sets the value of the '{@link srf.transpiler.fortxtrans.fortXTrans.ArrayInit#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(SimpleName value);

  /**
   * Returns the value of the '<em><b>Sizes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sizes</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sizes</em>' containment reference.
   * @see #setSizes(ExprList)
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getArrayInit_Sizes()
   * @model containment="true"
   * @generated
   */
  ExprList getSizes();

  /**
   * Sets the value of the '{@link srf.transpiler.fortxtrans.fortXTrans.ArrayInit#getSizes <em>Sizes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sizes</em>' containment reference.
   * @see #getSizes()
   * @generated
   */
  void setSizes(ExprList value);

  /**
   * Returns the value of the '<em><b>Filler</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Filler</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filler</em>' containment reference.
   * @see #setFiller(QualifiedName)
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getArrayInit_Filler()
   * @model containment="true"
   * @generated
   */
  QualifiedName getFiller();

  /**
   * Sets the value of the '{@link srf.transpiler.fortxtrans.fortXTrans.ArrayInit#getFiller <em>Filler</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filler</em>' containment reference.
   * @see #getFiller()
   * @generated
   */
  void setFiller(QualifiedName value);

} // ArrayInit
