/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package srf.transpiler.fortxtrans.fortXTrans;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Front</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.ExprFront#getAdd <em>Add</em>}</li>
 * </ul>
 *
 * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getExprFront()
 * @model
 * @generated
 */
public interface ExprFront extends EObject
{
  /**
   * Returns the value of the '<em><b>Add</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Add</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add</em>' containment reference.
   * @see #setAdd(CommaExpr)
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getExprFront_Add()
   * @model containment="true"
   * @generated
   */
  CommaExpr getAdd();

  /**
   * Sets the value of the '{@link srf.transpiler.fortxtrans.fortXTrans.ExprFront#getAdd <em>Add</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Add</em>' containment reference.
   * @see #getAdd()
   * @generated
   */
  void setAdd(CommaExpr value);

} // ExprFront
