/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package srf.transpiler.fortxtrans.fortXTrans;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Id Or Tuple</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.IdOrTuple#getBid <em>Bid</em>}</li>
 * </ul>
 *
 * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getIdOrTuple()
 * @model
 * @generated
 */
public interface IdOrTuple extends EObject
{
  /**
   * Returns the value of the '<em><b>Bid</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bid</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bid</em>' attribute list.
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getIdOrTuple_Bid()
   * @model unique="false"
   * @generated
   */
  EList<String> getBid();

} // IdOrTuple
