/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package srf.transpiler.fortxtrans.fortXTrans;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Init Val</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.InitVal#getMut <em>Mut</em>}</li>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.InitVal#getLit <em>Lit</em>}</li>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.InitVal#getImmut <em>Immut</em>}</li>
 * </ul>
 *
 * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getInitVal()
 * @model
 * @generated
 */
public interface InitVal extends EObject
{
  /**
   * Returns the value of the '<em><b>Mut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mut</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mut</em>' attribute.
   * @see #setMut(String)
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getInitVal_Mut()
   * @model
   * @generated
   */
  String getMut();

  /**
   * Sets the value of the '{@link srf.transpiler.fortxtrans.fortXTrans.InitVal#getMut <em>Mut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mut</em>' attribute.
   * @see #getMut()
   * @generated
   */
  void setMut(String value);

  /**
   * Returns the value of the '<em><b>Lit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lit</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lit</em>' containment reference.
   * @see #setLit(LiteralTuple)
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getInitVal_Lit()
   * @model containment="true"
   * @generated
   */
  LiteralTuple getLit();

  /**
   * Sets the value of the '{@link srf.transpiler.fortxtrans.fortXTrans.InitVal#getLit <em>Lit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lit</em>' containment reference.
   * @see #getLit()
   * @generated
   */
  void setLit(LiteralTuple value);

  /**
   * Returns the value of the '<em><b>Immut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Immut</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Immut</em>' attribute.
   * @see #setImmut(String)
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getInitVal_Immut()
   * @model
   * @generated
   */
  String getImmut();

  /**
   * Sets the value of the '{@link srf.transpiler.fortxtrans.fortXTrans.InitVal#getImmut <em>Immut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Immut</em>' attribute.
   * @see #getImmut()
   * @generated
   */
  void setImmut(String value);

} // InitVal
