/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package srf.transpiler.fortxtrans.fortXTrans;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
} // Model
