/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package srf.transpiler.fortxtrans.fortXTrans;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>No Newline Var WTypes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.NoNewlineVarWTypes#getSingle <em>Single</em>}</li>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.NoNewlineVarWTypes#getArrsize <em>Arrsize</em>}</li>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.NoNewlineVarWTypes#getMultiple <em>Multiple</em>}</li>
 * </ul>
 *
 * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getNoNewlineVarWTypes()
 * @model
 * @generated
 */
public interface NoNewlineVarWTypes extends EObject
{
  /**
   * Returns the value of the '<em><b>Single</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Single</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Single</em>' containment reference.
   * @see #setSingle(NoNewlineVarWType)
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getNoNewlineVarWTypes_Single()
   * @model containment="true"
   * @generated
   */
  NoNewlineVarWType getSingle();

  /**
   * Sets the value of the '{@link srf.transpiler.fortxtrans.fortXTrans.NoNewlineVarWTypes#getSingle <em>Single</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Single</em>' containment reference.
   * @see #getSingle()
   * @generated
   */
  void setSingle(NoNewlineVarWType value);

  /**
   * Returns the value of the '<em><b>Arrsize</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arrsize</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arrsize</em>' containment reference.
   * @see #setArrsize(ExprList)
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getNoNewlineVarWTypes_Arrsize()
   * @model containment="true"
   * @generated
   */
  ExprList getArrsize();

  /**
   * Sets the value of the '{@link srf.transpiler.fortxtrans.fortXTrans.NoNewlineVarWTypes#getArrsize <em>Arrsize</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arrsize</em>' containment reference.
   * @see #getArrsize()
   * @generated
   */
  void setArrsize(ExprList value);

  /**
   * Returns the value of the '<em><b>Multiple</b></em>' containment reference list.
   * The list contents are of type {@link srf.transpiler.fortxtrans.fortXTrans.NoNewlineVarWType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Multiple</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiple</em>' containment reference list.
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getNoNewlineVarWTypes_Multiple()
   * @model containment="true"
   * @generated
   */
  EList<NoNewlineVarWType> getMultiple();

} // NoNewlineVarWTypes
