/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package srf.transpiler.fortxtrans.fortXTrans;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Paran</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.Paran#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getParan()
 * @model
 * @generated
 */
public interface Paran extends Expr
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(ExprList)
   * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getParan_Exp()
   * @model containment="true"
   * @generated
   */
  ExprList getExp();

  /**
   * Sets the value of the '{@link srf.transpiler.fortxtrans.fortXTrans.Paran#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(ExprList value);

} // Paran
