/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package srf.transpiler.fortxtrans.fortXTrans;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Qualified</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage#getQualified()
 * @model
 * @generated
 */
public interface Qualified extends LiteralTuple
{
} // Qualified
