/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package srf.transpiler.fortxtrans.fortXTrans.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import srf.transpiler.fortxtrans.fortXTrans.AliasedAPIName;
import srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage;
import srf.transpiler.fortxtrans.fortXTrans.QualifiedName;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Aliased API Name</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.impl.AliasedAPINameImpl#getOrig <em>Orig</em>}</li>
 *   <li>{@link srf.transpiler.fortxtrans.fortXTrans.impl.AliasedAPINameImpl#getAsName <em>As Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AliasedAPINameImpl extends MinimalEObjectImpl.Container implements AliasedAPIName
{
  /**
   * The cached value of the '{@link #getOrig() <em>Orig</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOrig()
   * @generated
   * @ordered
   */
  protected QualifiedName orig;

  /**
   * The default value of the '{@link #getAsName() <em>As Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAsName()
   * @generated
   * @ordered
   */
  protected static final String AS_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAsName() <em>As Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAsName()
   * @generated
   * @ordered
   */
  protected String asName = AS_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AliasedAPINameImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FortXTransPackage.Literals.ALIASED_API_NAME;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public QualifiedName getOrig()
  {
    return orig;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOrig(QualifiedName newOrig, NotificationChain msgs)
  {
    QualifiedName oldOrig = orig;
    orig = newOrig;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FortXTransPackage.ALIASED_API_NAME__ORIG, oldOrig, newOrig);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOrig(QualifiedName newOrig)
  {
    if (newOrig != orig)
    {
      NotificationChain msgs = null;
      if (orig != null)
        msgs = ((InternalEObject)orig).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FortXTransPackage.ALIASED_API_NAME__ORIG, null, msgs);
      if (newOrig != null)
        msgs = ((InternalEObject)newOrig).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FortXTransPackage.ALIASED_API_NAME__ORIG, null, msgs);
      msgs = basicSetOrig(newOrig, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FortXTransPackage.ALIASED_API_NAME__ORIG, newOrig, newOrig));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAsName()
  {
    return asName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAsName(String newAsName)
  {
    String oldAsName = asName;
    asName = newAsName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FortXTransPackage.ALIASED_API_NAME__AS_NAME, oldAsName, asName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FortXTransPackage.ALIASED_API_NAME__ORIG:
        return basicSetOrig(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FortXTransPackage.ALIASED_API_NAME__ORIG:
        return getOrig();
      case FortXTransPackage.ALIASED_API_NAME__AS_NAME:
        return getAsName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FortXTransPackage.ALIASED_API_NAME__ORIG:
        setOrig((QualifiedName)newValue);
        return;
      case FortXTransPackage.ALIASED_API_NAME__AS_NAME:
        setAsName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FortXTransPackage.ALIASED_API_NAME__ORIG:
        setOrig((QualifiedName)null);
        return;
      case FortXTransPackage.ALIASED_API_NAME__AS_NAME:
        setAsName(AS_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FortXTransPackage.ALIASED_API_NAME__ORIG:
        return orig != null;
      case FortXTransPackage.ALIASED_API_NAME__AS_NAME:
        return AS_NAME_EDEFAULT == null ? asName != null : !AS_NAME_EDEFAULT.equals(asName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (asName: ");
    result.append(asName);
    result.append(')');
    return result.toString();
  }

} //AliasedAPINameImpl
