/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package srf.transpiler.fortxtrans.fortXTrans.impl;

import org.eclipse.emf.ecore.EClass;

import srf.transpiler.fortxtrans.fortXTrans.FortXTransPackage;
import srf.transpiler.fortxtrans.fortXTrans.MultExpr;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Mult Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MultExprImpl extends ExprImpl implements MultExpr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MultExprImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FortXTransPackage.Literals.MULT_EXPR;
  }

} //MultExprImpl
