/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package srf.transpiler.fortxtrans;

import srf.transpiler.fortxtrans.AbstractFortXTransRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FortXTransRuntimeModule extends AbstractFortXTransRuntimeModule {
}
