/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package org.example.domainmodel.scoping;

import org.example.domainmodel.scoping.AbstractDomainModelScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DomainModelScopeProvider extends AbstractDomainModelScopeProvider {
}
